// Ping-pong a counter between two processes.
// Only need to start one of these -- splits into two, crudely.

#include <inc/string.h>
#include <inc/lib.h>

envid_t dumbfork(void);

void
umain(int argc, char **argv)
{
	envid_t who;
	int i;

	// fork a child process
	who = dumbfork();

	// print a message and yield to the other a few times
	for (i = 0; i < (who ? 10 : 20); i++) {
		cprintf("%d: I am the %s!\n", i, who ? "parent" : "child");
		sys_yield();
	}
}

void
duppage(envid_t dstenv, void *addr)
{
	int r;

	/* Note balvisio:
	* When dstenv is equal to 0 (3rd parameter
	* of sys_page_map) it refers to the current
	* environment. (see /kern/env.c/envid2env)
	* Exaplantion of dumbfork:
	* 1. sys_page_alloc: This is call is allocate a
	* a page of memory for the child.
	*
	* 2. sys_page_map: maps the address space of the
	* child at address 'addr' to the memory address space
	* of the current environment (the parent) at parents
	* address UTEMP
	*
	* 3. memmove: Copies from the parent address space PGSIZE
	* bytes starting at address 'addr' to UTEMP.
	*
	* What these achieves is that the child gets a copy of a
	* page of memory of its parent address space.
	*
	* balvisio: The way it works is:
	* 1st: with page_alloc we allocated a page of physical
	* memory to address addr.
	*
	* 2nd: with page_map : Copy a page mapping (not the contents of a page!)
	* from father space to chils, leaving a memory 
	* sharing arrangement in place so that the new and the old mappings 
	* BOTH refer to the same page of physical memory.
	* 
	* balvisio: At this point both address space (child and parent) are pointing
	* to the same physical page. (the ref count of the physical page is at this
	* point equal to 2)
	*
	* 3rd: With the unmap the father doesn't point to the physical page
	* anymore but the child is still pointing to it. Thus, the physical is
	* not freed is still retained (refcount = 1) and it is only referenced
	* now by the child process.
	*  
	*/

	// This is NOT what you should do in your fork.
	if ((r = sys_page_alloc(dstenv, addr, PTE_P|PTE_U|PTE_W)) < 0)
		panic("sys_page_alloc: %e", r);
	//Map from child -> father
	if ((r = sys_page_map(dstenv, addr, 0, UTEMP, PTE_P|PTE_U|PTE_W)) < 0)
		panic("sys_page_map: %e", r);
	//dst, src, len: copy from addr to UTEMP
	memmove(UTEMP, addr, PGSIZE);
	if ((r = sys_page_unmap(0, UTEMP)) < 0)
		panic("sys_page_unmap: %e", r);
}

envid_t
dumbfork(void)
{
	envid_t envid;
	uint8_t *addr;
	int r;
	extern unsigned char end[];

	// Allocate a new child environment.
	// The kernel will initialize it with a copy of our register state,
	// so that the child will appear to have called sys_exofork() too -
	// except that in the child, this "fake" call to sys_exofork()
	// will return 0 instead of the envid of the child.
	envid = sys_exofork();
	if (envid < 0)
		panic("sys_exofork: %e", envid);
	if (envid == 0) {
		// We're the child.
		// The copied value of the global variable 'thisenv'
		// is no longer valid (it refers to the parent!).
		// Fix it and return 0.
		cprintf("I am the child \n");
		thisenv = &envs[ENVX(sys_getenvid())];
		return 0;
	}

	// We're the parent.
	// Eagerly copy our entire address space into the child.
	// This is NOT what you should do in your fork implementation.

	/* balvisio:
	* 'end' is a magic symbol automatically generated by the linker,
	* which points to the end of the dumbfork bss segment.
	* the first virtual address that the linker did *not* assign
	* to any code or global variables. (balvisio: Not sure though
	* need to confirm. In dumbfork it is 0x802008)
	*/
	for (addr = (uint8_t*) UTEXT; addr < end; addr += PGSIZE)
		duppage(envid, addr);

	// Also copy the stack we are currently running on.
	duppage(envid, ROUNDDOWN(&addr, PGSIZE));


	// Start the child environment running
	if ((r = sys_env_set_status(envid, ENV_RUNNABLE)) < 0)
		panic("sys_env_set_status: %e", r);

	return envid;
}

